apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  annotations:
    checksum/config: {{ .Values.config | toJson | sha256sum }}
type: Opaque
data:
  application-override.json: |
    {{ .Values.config | toJson | b64enc }}
